### ISSUE TITLE
XAML Islands - UWP controls hosted in XAML host with text selection such as textbox don't show touch text selection grips when DPI scaling level is above 100%

### ISSUE THREAD

**Issue by aquinn39** [windows-toolkit/Microsoft.Toolkit.Win32#118]
## I'm submitting a...

- Bug report (I searched for similar issues and did not find one) 
 

## Current behavior

When tapping on text and the DPI scaling level is above 100%, text selection grips do not show
![XAML Islands no touch text selection grips](https://user-images.githubusercontent.com/43898231/57297947-473d6000-7114-11e9-897a-0105f66b026b.png)

## Expected behavior

When tapping on text the selection grips should show
![XAML Islands touch text selection grips](https://user-images.githubusercontent.com/43898231/57297978-5ae8c680-7114-11e9-957c-199c865f9eec.png)

## Minimal reproduction of the problem with instructions

Create a WPF or Forms app with an XAML host who's content contains a control with selectable text. Go to Settings and make sure the DPI scaling level is 125% or higher. Text selection grips won't show when you select text in the XAML host using touch. If you set the DPI scaling level to 100%, they will show.

## Environment

```
Nuget Package(s): 
Microsoft.Toolkit.Forms.UI.XamlHost - 6.0.0-preview5
Microsoft.Toolkit.Wpf.UI.XamlHost - 6.0.0-preview5
Microsoft.Windows.SDK.Contracts - 10.0.18362.2002-preview


Windows 10 Build Number:
[x] Insider Build (build number: 18362.86)

App min and target version:
[x] Insider Build (18358.0)

Device form factor:
[x] Desktop

Visual Studio 
[x] 2019 (version: 16.0.3)


```

**Comment by azchohfi** [comment]
Could you test this with the newest MyGet package? 168.

**Comment by michael-hawker** [comment]
@aquinn39 this should be fixed in the new packages.  Can you test with the new preview packages?  A lot of DPI issues have been resolved.

**Comment by aquinn39** [comment]
I tested it with Preview 7.1 and the issue still occurs on Windows 10 1903 (on build 18362.329). I noticed that it is fixed in the Windows 10 20H1 insider preview builds. Not sure about 19H2 as I have not tested. I'd also like to point out that the issue does not occur with selectable textblocks, only with texboxes. Another thing I noticed is that this same issue also occurs in the Windows 10 Sticky Notes app (along with some other XAML host related issues, which is interesting). It seems to me like an OS update is required to fix this, rather than an update to the XAML host packages.

**Comment by michael-hawker** [comment]
Thanks for the updated info @aquinn39.  @marb2000 can you confirm this is an OS fix required?  Do you know if it'll be back-ported via servicing?

**Comment by marb2000** [comment]
Servicing is mainly for critical and severe bugs, this is not one of them. I believe this will be pushed back, so it is highly unlikely this bug will be service to 19h1. However, it could be fixed on WinUI 3. @aquinn39 can you open a bug on [WinUI](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose) backlog?

**Comment by marb2000** [comment]
I have created this bug https://github.com/microsoft/microsoft-ui-xaml/issues/1341 in WinUI.
